version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      PGUSER: pixelpay
      POSTGRES_USER: pixelpay
      POSTGRES_PASSWORD: oot123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql